// packages/function-unit/src/FunctionItem.vue
<script lang="ts" setup>
import { defineProps, ref } from 'vue'
import { ElTooltip } from 'element-plus'
import type { FunctionItemProps } from '../typings'

const { description, initialWidth } = defineProps<FunctionItemProps>()

const currentWidth = ref(initialWidth)
</script>

<template>
  <ElTooltip :content="description">
    <div class="function-item" :style="{ width: currentWidth }">
      <slot />
    </div>
  </ElTooltip>
</template>

<style lang="scss">
.function-item {
  display: flex;
  flex-wrap: nowrap;
  justify-content: space-between;
  align-items: center;
}
</style>

// packages/explorer/src/FunctionItem.tsx
import { Flex, Tooltip } from 'antd'
import React, { useImperativeHandle, useState } from 'react'

export interface FunctionItemProps extends React.HTMLAttributes<HTMLDivElement> {
  level: number
  description: string
  initialWidth: number
}

export default React.forwardRef(function ({
  description,
  children,
  initialWidth,
  
}: FunctionItemProps, ref) {

  const [itemWidth, setItemWidth] = useState(initialWidth)

  useImperativeHandle(ref, () => {
    setItemWidth
  })
  
  return (
    <Tooltip title={description}>
      <Flex align="center" justify="space-between">
        {children}
      </Flex>
    </Tooltip>
  )
})
